name: update dags

on:
  workflow_dispatch:

jobs:
  check-instance-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: |
          INSTANCE_STATE=$(aws ec2 describe-instance-status --include-all-instances --instance-id i-01933dcba1a6a289a --output text | grep -o 'pending\|running\|shutting-down\|terminated\|stopping\|stopped')
          echo "INSTANCE_STATE=$INSTANCE_STATE" >> "$GITHUB_OUTPUT"

  turn-on-ec2:
    runs-on: ubuntu-latest
    needs: check-instance-status
    if: ${{ needs.check-instance-status.outputs.INSTANCE_STATUS == "stopped" }}
    steps:
      - name: Start AWS EC2
        run: aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
#
#  upload-dags:
